- job-template:
    name: mcp-k8s-images-pipeline
    description: |
      Kubernetes unit and integration tests images build job
    project-type: pipeline
    concurrent: false
    parameters:
      - string:
          name: DOCKER_REGISTRY
          default: '{docker-dev-virtual}'
          description: 'Docker registry for test images'
      - string:
          name: GERRIT_HOST
          default: '{gerrit-host}'
          description: 'Gerrit hostname'
    dsl:
      !include-raw-escape: mcp-k8s-images-pipeline.groovy
