- job-template:
    name: mcp-k8s-images-pipeline
    description: |
      Kubernetes unit and integration tests images build job
    project-type: workflow
    concurrent: false
    parameters:
      - string:
          name: DOCKER_REGISTRY
          default: '{k8s-tests-registry}'
          description: 'Docker registry for tests'
      - string:
          name: DOCKER_REPOSITORY
          default: 'k8s-tests-images'
          desription: 'Docker repository name'
      - string:
          name: GERRIT_HOST
          default: '{gerrit-host}'
          description: 'Gerrit hostname'
    dsl:
      !include-raw-escape: mcp-k8s-images-pipeline.groovy
