- job-template:
    name: mcp-k8s-test-pipeline
    description: |
      Kubernetes tests pipeline
    project-type: workflow
    concurrent: true
    parameters:
      - string:
          name: KUBE_DOCKER_REGISTRY
          default: '{docker-dev-virtual}'
          description: 'Docker registry for binaries and images'
      - string:
          name: CALICO_DOCKER_REGISTRY
          default: '{docker-prod-virtual}'
          description: 'Docker registry for published Calico images'
      - string:
          name: K8S_BASE_IMAGE
          default: 'debian:jessie'
          description: 'Base Docker image to build k8s'
      - string:
          name: ARTIFACTORY_URL
          default: '{artifactory-url}'
          desription: 'Custom Artifactory URL'
      - string:
          name: DOCKER_IMAGE_UNIT
          default: '{docker-prod-virtual}/mirantis/k8s-tests-images/k8s-tests-unit:latest'
          desription: 'Docker image for k8s unit tests'
      - string:
          name: DOCKER_IMAGE_INTEGRATION
          default: '{docker-prod-virtual}/mirantis/k8s-tests-images/k8s-tests-integration:latest'
          desription: 'Docker image for k8s integration tests'
      - string:
          name: CALICO_CNI_IMAGE_REPO
          default: 'calico/cni'
          description: 'Custom calico/cni image repository'
      - string:
          name: CALICO_CNI_IMAGE_TAG
          default: 'v1.5.1'
          description: 'Custom calico/cni image tag'
      - bool:
          name: CALICO_DOWNSTREAM
          default: true
          description: 'Use Calico downstream'
      - string:
          name: CALICO_VER
          default: 'mcp'
          description: 'Custom Calico version'
    triggers:
      - gerrit:
          trigger-on:
            - patchset-created-event
            - comment-added-contains-event:
                comment-contains-value: '(recheck|reverify)'
          projects:
            - project-compare-type: PLAIN
              project-pattern: kubernetes/kubernetes
              branches:
                - branch-compare-type: ANT
                  branch-pattern: '**'
          custom-url: '* $JOB_NAME $BUILD_URL'
    dsl:
      !include-raw-escape: mcp-k8s-test-pipeline.groovy
