- job-template:
    name: mcp-k8s-hyperkube-custom
    description: |
      Build Kubernetes Hyperkube from git SHA
    project-type: workflow
    concurrent: true
    parameters:
      - string:
          name: GIT_SHA
          description: 'Git SHA of some commit'
      - string:
          name: GERRIT_HOST
          default: '{gerrit-host}'
          desription: 'Gerrit host'
      - string:
          name: MANUAL_EVENT_TYPE
          default: 'hyperkube-build-by-sha'
          description: 'Event type for job'
      - string:
          name: KUBE_DOCKER_REGISTRY
          default: '{docker-dev-virtual}'
          description: 'Docker registry for binaries and images'
      - string:
          name: K8S_BASE_IMAGE
          default: '{docker-prod-virtual}/mirantis/base-images/debian-base:20161223134732'
          description: 'Base Docker image to build k8s'
      - string:
          name: CALICO_CNI
          default: ''
          description: 'Custom Calico CNI url'
      - string:
          name: CALICO_IPAM
          default: ''
          description: 'Custom Calico IPAM url'
      - bool:
          name: CALICO_DOWNSTREAM
          default: true
          description: 'Use Calico downstream'
      - string:
          name: CALICO_VER
          default: 'mcp'
          description: 'Custom Calico version'

    properties:
      - authorization-allow-group:
          group_name: 'mcp-k8s'

    dsl:
      !include-raw-escape: mcp-k8s-test-pipeline.groovy
