- job-template:
    name: mcp-k8s-hyperkube-test-all
    description: 'Run MCP system tests for "hyperkube" project'
    node: k8s
    concurrent: true
    properties:
      - throttle:
          max-per-node: 1
          option: project
    parameters:
      - string:
          name: GERRIT_REFSPEC
          default: 'refs/heads/master'
    properties-data-file: 'artifacts-data.txt'
    builders:
      - inject:
          properties-content: |
            KUBE_DOCKER_REGISTRY={mcp-k8s-ci-registry}
            KUBE_DOCKER_REPOSITORY=hyperkube-amd64
            KUBE_DOCKER_OWNER=jenkins
            ARTIFACTORY_URL={artifactory-url}
            ARTIFACTORY_USER_EMAIL=jenkins@mcp-ci-artifactory
            GERRIT_HOST={gerrit-host}
            HYPERKUBE_ARTIFACTS_FILE={properties-data-file}
            ONLY_WAIT_FOR_ARTIFACTS=true
      - shell:
          !include-raw-escape: ../../builders/mcp-k8s-hyperkube.sh

      - trigger-builds:
          - project: 'calico.system-test.deploy'
            current-parameters: true
            property-file: '{properties-data-file}'
            property-file-fail-on-missing: false
            block: true
    wrappers:
      - workspace-cleanup
      - ssh-agent-credentials:
          users:
            - 'mcp-ci-gerrit'
    triggers:
      - gerrit:
          trigger-on:
            - patchset-created-event
            - comment-added-contains-event:
                comment-contains-value: '(recheck|reverify)'
          projects:
            - project-compare-type: PLAIN
              project-pattern: kubernetes/kubernetes
              branches:
                - branch-compare-type: ANT
                  branch-pattern: '**'
          custom-url: '* $JOB_NAME $BUILD_URL'
          skip-vote:
              successful: true
              failed: true
              unstable: true
              notbuilt: true
    publishers:
      - archive:
          artifacts: 'hyperkube_image*.yaml'
          allow-empty: true
