- job-template:
    name: 'mcp-test-deploy-k8s-cluster-{cluster}'
    description: |
      Test deployment of Kubernetes Cluster using Kargo
    project-type: pipeline
    concurrent: true
    parameters:
      - string:
          name: GERRIT_HOST
          default: '{gerrit-host}'
      - string:
          name: CLUSTER_NAME
          default: '{cluster}'
      - string:
          name: UNDERLAY
          default: 'fuel-devops'
      - string:
          name: INV_SOURCE
          default: 'json'
          description: 'Inventory format for deployment: json or ansible_inventory'
      - string:
          name: KARGO_COMMIT
          default: 'master'
          description: 'Provide commit from which to checkout kargo'
      - string:
          name: FUEL_CCP_INSTALLER_COMMIT
          default: 'master'
          description: "Provide commit from which to checkout fuel-ccp-installer"
      - string:
          name: FUEL_CCP_INSTALLER_REFS
          default: 'none'
          description: |
            Refspecs in UPSTREAM gerrit for commits in fuel-ccp-installer project<br>
            For example: refs/changes/10/55310/1 refs/changes/10/55310/2

      - bool:
          name: ERASE_ENV
          default: true
          description: 'Erase env after deployment'
    dsl:
      !include-raw-escape: test-k8s-deployment.groovy
    triggers:
      - timed: '15 */4 * * *'
